<a href="https://colab.research.google.com/github/LucyKinyua/Week4_MS/blob/main/Moringa_Data_Science_Prep_W4_Independent_Project_2021_05_Lucy_Kinyua_Python_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Overview

In this week's independent project, you will be working as a data scientist working for an electric car-sharing service company. You have been tasked to process stations data to understand electric car usage over time by solving for the following research question;

Research Question

- Identify the most popular hour of the day for picking up a shared electric car (Bluecar) in the city of Paris over the month of April 2018.

Bonus Questions (Optional)

- What is the most popular hour for returning cars?
- What station is the most popular?
 - Overall?
 - At the most popular picking hour?
- What postal code is the most popular for picking up Blue cars? Does the most popular station belong to that postal code?
 - Overall?
 - At the most popular picking hour?
- Do the results change if you consider Utilib and Utilib 1.4 instead of Blue cars?

# Importing Python libraries and loading the dataset

In [1]:
# Importing the Pandas and NumPy libraries;
# 
import pandas as pd
import numpy as np

In [2]:
# Creating a DataFrame from the Autolib dataset;
# 
autolib_df = pd.read_csv('Autolib_dataset (2).csv', delimiter = ',')
autolib_df

                                 Address  Cars  ...  hour  minute
0                    2 Avenue de Suffren     0  ...    11      43
1              145 Rue Raymond Losserand     6  ...     7      24
2       2 Avenue John Fitzgerald Kennedy     3  ...    20      14
3                 51 Rue EugÃ¨ne OudinÃ©     3  ...     4      37
4     6 avenue de la Porte de Champerret     3  ...    17      23
...                                  ...   ...  ...   ...     ...
4995                 8 avenue MÃ©nelotte     2  ...    11      26
4996                   37 rue de Dantzig     4  ...    16      56
4997                      142 rue du Bac     1  ...     7       1
4998         2 avenue du Val de Fontenay     2  ...    17      27
4999                 5 Rue Henry Brisson     4  ...    10       2

[5000 rows x 25 columns]

# Data Understanding

In [3]:
# Previewing the first 10 rows of the DataFrame;
# 
autolib_df.head(10)

                              Address  Cars  Bluecar counter  ...  day  hour  minute
0                 2 Avenue de Suffren     0                0  ...    8    11      43
1           145 Rue Raymond Losserand     6                6  ...    6     7      24
2    2 Avenue John Fitzgerald Kennedy     3                3  ...    3    20      14
3              51 Rue EugÃ¨ne OudinÃ©     3                3  ...    4     4      37
4  6 avenue de la Porte de Champerret     3                3  ...    8    17      23
5                8 Boulevard Voltaire     0                0  ...    6     7       2
6                      37 rue Leblanc     0                0  ...    8    18      20
7         17 Rue des Luaps ProlongÃ©e     3                3  ...    4    22      13
8               34 avenue Jean Moulin     1                1  ...    2    22      58
9        41 boulevard de Rochechouart     6                6  ...    4    15       2

[10 rows x 25 columns]

In [4]:
# Checking the shape (that is, the number of rows and columns) of the DataFrame;
# 
autolib_df.shape

(5000, 25)

In [5]:
# Printing out the column names;
# 
autolib_df.columns

Index(['Address', 'Cars', 'Bluecar counter', 'Utilib counter',
       'Utilib 1.4 counter', 'Charge Slots', 'Charging Status', 'City',
       'Displayed comment', 'ID', 'Kind', 'Geo point', 'Postal code',
       'Public name', 'Rental status', 'Scheduled at', 'Slots', 'Station type',
       'Status', 'Subscription status', 'year', 'month', 'day', 'hour',
       'minute'],
      dtype='object')

In [6]:
# Accessing information about our DataFrame;
# 
autolib_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 25 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Address              5000 non-null   object
 1   Cars                 5000 non-null   int64
 2   Bluecar counter      5000 non-null   int64
 3   Utilib counter       5000 non-null   int64
 4   Utilib 1.4 counter   5000 non-null   int64
 5   Charge Slots         5000 non-null   int64
 6   Charging Status      5000 non-null   object
 7   City                 5000 non-null   object
 8   Displayed comment    111 non-null    object
 9   ID                   5000 non-null   object
 10  Kind                 5000 non-null   object
 11  Geo point            5000 non-null   object
 12  Postal code          5000 non-null   int64
 13  Public name          5000 non-null   object
 14  Rental status        5000 non-null   object
 15  Scheduled at         47 non-null     object
 16  Slots                5000 non-null   int64
 17  Station type         5000 non-null   object
 18  Status               5000 non-null   object
 19  Subscription status  5000 non-null   object
 20  year                 5000 non-null   int64
 21  month                5000 non-null   int64
 22  day                  5000 non-null   int64
 23  hour                 5000 non-null   int64
 24  minute               5000 non-null   int64
dtypes: int64(12), object(13)
memory usage: 976.7+ KB

# Data Preparation

In [7]:
# Checking the dataset for null values;
# 
autolib_df.isnull().sum()

Address                   0
Cars                      0
Bluecar counter           0
Utilib counter            0
Utilib 1.4 counter        0
Charge Slots              0
Charging Status           0
City                      0
Displayed comment      4889
ID                        0
Kind                      0
Geo point                 0
Postal code               0
Public name               0
Rental status             0
Scheduled at           4953
Slots                     0
Station type              0
Status                    0
Subscription status       0
year                      0
month                     0
day                       0
hour                      0
minute                    0
dtype: int64

In [8]:
# There are a statistically significant number of missing/null values in the two columns,
# That is, 'Displayed comment' and 'Scheduled at'
# Therefore, we could drop them;
# 
autolib_df.drop(['Displayed comment', 'Scheduled at'], axis=1, inplace=True)
autolib_df.head(10)

                              Address  Cars  Bluecar counter  ...  day  hour  minute
0                 2 Avenue de Suffren     0                0  ...    8    11      43
1           145 Rue Raymond Losserand     6                6  ...    6     7      24
2    2 Avenue John Fitzgerald Kennedy     3                3  ...    3    20      14
3              51 Rue EugÃ¨ne OudinÃ©     3                3  ...    4     4      37
4  6 avenue de la Porte de Champerret     3                3  ...    8    17      23
5                8 Boulevard Voltaire     0                0  ...    6     7       2
6                      37 rue Leblanc     0                0  ...    8    18      20
7         17 Rue des Luaps ProlongÃ©e     3                3  ...    4    22      13
8               34 avenue Jean Moulin     1                1  ...    2    22      58
9        41 boulevard de Rochechouart     6                6  ...    4    15       2

[10 rows x 23 columns]

In [9]:
# Checking the shape of the DataFrame to confirm the change has taken effect;
# 
autolib_df.shape

(5000, 23)

In [12]:
# Also, note that some columns are either redundant or irrelevant, e.g.,
# 'Cars' and 'Bluecar counter' always have the same value. Therefore, we could drop 'Cars'
# 'Address', 'ID', 'Geo point', are irrelevant columns
# Therefore, we could drop and leave one of the columns as well;
# 
# 
autolib_df.drop(['Cars',], axis=1, inplace=True)
autolib_df.head(10)

                              Address  Bluecar counter  ...  hour  minute
0                 2 Avenue de Suffren                0  ...    11      43
1           145 Rue Raymond Losserand                6  ...     7      24
2    2 Avenue John Fitzgerald Kennedy                3  ...    20      14
3              51 Rue EugÃ¨ne OudinÃ©                3  ...     4      37
4  6 avenue de la Porte de Champerret                3  ...    17      23
5                8 Boulevard Voltaire                0  ...     7       2
6                      37 rue Leblanc                0  ...    18      20
7         17 Rue des Luaps ProlongÃ©e                3  ...    22      13
8               34 avenue Jean Moulin                1  ...    22      58
9        41 boulevard de Rochechouart                6  ...    15       2

[10 rows x 22 columns]

In [ ]:
# Checking the shape of the DataFrame to confirm the change has taken effect;
# 
autolib_df.shape

In [10]:
# Describing the statistical properties of the integer values in the DataFrame;
# 
autolib_df.describe()

              Cars  Bluecar counter  ...         hour       minute
count  5000.000000      5000.000000  ...  5000.000000  5000.000000
mean      2.333600         2.333600  ...    11.509200    29.270000
std       2.035274         2.035274  ...     6.893549    17.231741
min       0.000000         0.000000  ...     0.000000     0.000000
25%       0.000000         0.000000  ...     6.000000    14.000000
50%       2.000000         2.000000  ...    11.000000    29.000000
75%       4.000000         4.000000  ...    18.000000    44.000000
max       7.000000         7.000000  ...    23.000000    59.000000

[8 rows x 12 columns]

In [ ]:
# 
#

# Analysis

In [10]:
# We are only interested in data in the city of Paris
# 
autolib_df.loc[autolib_df['City'] == 'Paris']

                                 Address  Cars  ...  hour  minute
0                    2 Avenue de Suffren     0  ...    11      43
1              145 Rue Raymond Losserand     6  ...     7      24
3                 51 Rue EugÃ¨ne OudinÃ©     3  ...     4      37
4     6 avenue de la Porte de Champerret     3  ...    17      23
5                   8 Boulevard Voltaire     0  ...     7       2
...                                  ...   ...  ...   ...     ...
4992                     3 avenue d'Ivry     0  ...    23       1
4994                    15 rue de Rocroy     0  ...    20      49
4996                   37 rue de Dantzig     4  ...    16      56
4997                      142 rue du Bac     1  ...     7       1
4999                 5 Rue Henry Brisson     4  ...    10       2

[2816 rows x 23 columns]

In [7]:
# Accessing information about the first row in the dataset;
# 
autolib_df.iloc[0]

Address                2 Avenue de Suffren
Cars                                     0
Bluecar counter                          0
Utilib counter                           0
Utilib 1.4 counter                       0
Charge Slots                             0
Charging Status                nonexistent
City                                 Paris
Displayed comment                      NaN
ID                         paris-suffren-2
Kind                               STATION
Geo point                   48.857, 2.2917
Postal code                          75015
Public name                Paris/Suffren/2
Rental status                  operational
Scheduled at                           NaN
Slots                                    2
Station type                       station
Status                                  ok
Subscription status            nonexistent
year                                  2018
month                                    4
day                                      8
hour                                    11
minute                                  43
Name: 0, dtype: object

# Evaluation